Repository AY2223S1-CS2103T-T09-2/tp, pull requests merged in 2022-10, with the labels that each got.

#79 Branch add command
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/model/pet/Color.java
  src/main/java/seedu/address/model/pet/DateOfBirth.java
  src/main/java/seedu/address/model/pet/Height.java
  src/main/java/seedu/address/model/pet/Pet.java
  src/main/java/seedu/address/model/pet/PetCertificate.java
  src/main/java/seedu/address/model/pet/Species.java
  src/main/java/seedu/address/model/pet/UniquePetList.java
  src/main/java/seedu/address/model/pet/VaccinationStatus.java
  src/main/java/seedu/address/model/pet/Weight.java
  src/main/java/seedu/address/model/pet/exceptions/DuplicatePetException.java
  src/main/java/seedu/address/model/pet/exceptions/PetNotFoundException.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/test/java/seedu/address/model/person/UniquePetListTest.java
Labels: type.Task

#93 Update FindCommand Update FindCommandParser
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalBuyers.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Task

#147 Branch add command
  src/main/java/seedu/address/commons/core/index/UniqueId.java
  src/main/java/seedu/address/commons/core/index/UniqueIdGenerator.java
  src/main/java/seedu/address/logic/commands/AddBuyerCommand.java
  src/main/java/seedu/address/logic/commands/AddOrderCommand.java
  src/main/java/seedu/address/logic/commands/AddPetCommand.java
  src/main/java/seedu/address/logic/commands/AddSupplierCommand.java
  src/main/java/seedu/address/logic/parser/AddBuyerCommandParser.java
  src/main/java/seedu/address/logic/parser/AddPersonCommandParser.java
  src/main/java/seedu/address/logic/parser/AddSupplierCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/order/AdditionalRequests.java
  src/main/java/seedu/address/model/order/Order.java
  src/main/java/seedu/address/model/order/Request.java
  src/main/java/seedu/address/model/person/Buyer.java
  src/main/java/seedu/address/model/person/Supplier.java
  src/main/java/seedu/address/model/pet/Pet.java
  src/main/java/seedu/address/storage/JsonAdaptedBuyer.java
  src/main/java/seedu/address/storage/JsonAdaptedSupplier.java
  src/main/java/seedu/address/ui/BuyerCard.java
  src/test/java/seedu/address/model/person/BuyerTest.java
  src/test/java/seedu/address/model/person/SupplierTest.java
  src/test/java/seedu/address/storage/JsonAdaptedBuyerTest.java
  src/test/java/seedu/address/storage/JsonAdaptedSupplierTest.java
Labels: priority.High

#153 Update DG about the unique ID mechanism
  docs/DeveloperGuide.md
Labels: priority.Medium

#154 Update build.gradle
  build.gradle
Labels: priority.High

#145 Refactor, Branch list
  src/main/java/seedu/address/commons/core/index/UniqueId.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/commands/SortCommandUtil.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ListCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/order/Order.java
  src/main/java/seedu/address/model/order/Request.java
  src/main/java/seedu/address/model/order/UniqueOrderList.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Buyer.java
  src/main/java/seedu/address/model/person/Deliverer.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/Location.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/Phone.java
  src/main/java/seedu/address/model/person/Supplier.java
  src/main/java/seedu/address/model/pet/DateOfBirth.java
  src/main/java/seedu/address/model/pet/Pet.java
  src/main/java/seedu/address/model/pet/UniquePetList.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedBuyer.java
  src/main/java/seedu/address/storage/JsonAdaptedDeliverer.java
  src/main/java/seedu/address/storage/JsonAdaptedPet.java
  src/main/java/seedu/address/storage/JsonAdaptedSupplier.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/main/java/seedu/address/ui/BuyerCard.java
  src/main/java/seedu/address/ui/BuyerListPanel.java
  src/main/java/seedu/address/ui/DelivererCard.java
  src/main/java/seedu/address/ui/DelivererListPanel.java
  src/main/java/seedu/address/ui/MainListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PetCard.java
  src/main/java/seedu/address/ui/SupplierCard.java
  src/main/java/seedu/address/ui/SupplierListPanel.java
  src/test/java/seedu/address/logic/commands/AddBuyerCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/person/BuyerTest.java
  src/test/java/seedu/address/model/person/SupplierTest.java
  src/test/java/seedu/address/model/pet/PetTest.java
  src/test/java/seedu/address/model/pet/UniquePetListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedBuyerTest.java
  src/test/java/seedu/address/storage/JsonAdaptedDelivererTest.java
  src/test/java/seedu/address/storage/JsonAdaptedSupplierTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/seedu/address/testutil/TypicalPets.java
Labels: priority.High

#179 Branch match command
  src/main/java/seedu/address/logic/commands/MatchCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/MatchCommandParser.java
  src/main/java/seedu/address/model/order/Price.java
  src/main/java/seedu/address/model/order/PriceRange.java
  src/main/java/seedu/address/model/pet/PetGrader.java
Labels: priority.High

#182 Branch update ug
  docs/UserGuide.md
  docs/team/johndoe.md
Labels: priority.High

#187 Update UserGuide.md
  docs/UserGuide.md
Labels: priority.High

#198 Pass CI
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/model/order/AdditionalRequestsTest.java
Labels: priority.High

#199 Branch update ug
  src/test/java/seedu/address/model/order/AdditionalRequestsTest.java
Labels: priority.High

#206 Branch update ug
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/uniqueIdIllustration.png
Labels: priority.High

#208 Update UserGuide.md
  docs/UserGuide.md
Labels: priority.High

#299 Branch debug
  docs/UserGuide.md
  src/main/java/seedu/address/commons/core/Config.java
  src/main/java/seedu/address/logic/commands/addcommands/AddBuyerCommand.java
  src/main/java/seedu/address/logic/commands/addcommands/AddPetCommand.java
  src/main/java/seedu/address/logic/commands/addcommands/AddSupplierCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/ui/popupwindow/AddCommandPopupWindow.java
Labels: priority.High
